export type TLanguages = {
  name: string;
  value: string;
};

export const listOfLanguages: Array<TLanguages> = [
  { name: "Afrikaans", value: "af" },
  { name: "Albanian - shqip", value: "sq" },
  { name: "Amharic - አማርኛ", value: "am" },
  { name: "Arabic - العربية", value: "ar" },
  { name: "Aragonese - aragonés", value: "an" },
  { name: "Armenian - հայերեն", value: "hy" },
  { name: "Asturian - asturianu", value: "ast" },
  { name: "Azerbaijani - azərbaycan dili", value: "az" },
  { name: "Basque - euskara", value: "eu" },
  { name: "Belarusian - беларуская", value: "be" },
  { name: "Bengali - বাংলা", value: "bn" },
  { name: "Bosnian - bosanski", value: "bs" },
  { name: "Breton - brezhoneg", value: "br" },
  { name: "Bulgarian - български", value: "bg" },
  { name: "Catalan - català", value: "ca" },
  { name: "Central Kurdish - کوردی (دەستنوسی عەرەبی)", value: "ckb" },
  { name: "Chinese - 中文", value: "zh" },
  { name: "Chinese (Hong Kong) - 中文（香港）", value: "zh-HK" },
  { name: "Chinese (Simplified) - 中文（简体）", value: "zh-CN" },
  { name: "Chinese (Traditional) - 中文（繁體）", value: "zh-TW" },
  { name: "Corsican", value: "co" },
  { name: "Croatian - hrvatski", value: "hr" },
  { name: "Czech - čeština", value: "cs" },
  { name: "Danish - dansk", value: "da" },
  { name: "Dutch - Nederlands", value: "nl" },
  { name: "English", value: "en" },
  { name: "English (Australia)", value: "en-AU" },
  { name: "English (Canada)", value: "en-CA" },
  { name: "English (India)", value: "en-IN" },
  { name: "English (New Zealand)", value: "en-NZ" },
  { name: "English (South Africa)", value: "en-ZA" },
  { name: "English (United Kingdom)", value: "en-GB" },
  { name: "English (United States)", value: "en-US" },
  { name: "Esperanto - esperanto", value: "eo" },
  { name: "Estonian - eesti", value: "et" },
  { name: "Faroese - føroyskt", value: "fo" },
  { name: "Filipino", value: "fil" },
  { name: "Finnish - suomi", value: "fi" },
  { name: "French - français", value: "fr" },
  { name: "French (Canada) - français (Canada)", value: "fr-CA" },
  { name: "French (France) - français (France)", value: "fr-FR" },
  { name: "French (Switzerland) - français (Suisse)", value: "fr-CH" },
  { name: "Galician - galego", value: "gl" },
  { name: "Georgian - ქართული", value: "ka" },
  { name: "German - Deutsch", value: "de" },
  { name: "German (Austria) - Deutsch (Österreich)", value: "de-AT" },
  { name: "German (Germany) - Deutsch (Deutschland)", value: "de-DE" },
  { name: "German (Liechtenstein) - Deutsch (Liechtenstein)", value: "de-LI" },
  { name: "German (Switzerland) - Deutsch (Schweiz)", value: "de-CH" },
  { name: "Greek - Ελληνικά", value: "el" },
  { name: "Guarani", value: "gn" },
  { name: "Gujarati - ગુજરાતી", value: "gu" },
  { name: "Hausa", value: "ha" },
  { name: "Hawaiian - ʻŌlelo Hawaiʻi", value: "haw" },
  { name: "Hebrew - עברית", value: "he" },
  { name: "Hindi - हिन्दी", value: "hi" },
  { name: "Hungarian - magyar", value: "hu" },
  { name: "Icelandic - íslenska", value: "is" },
  { name: "Indonesian - Indonesia", value: "id" },
  { name: "Interlingua", value: "ia" },
  { name: "Irish - Gaeilge", value: "ga" },
  { name: "Italian - italiano", value: "it" },
  { name: "Italian (Italy) - italiano (Italia)", value: "it-IT" },
  { name: "Italian (Switzerland) - italiano (Svizzera)", value: "it-CH" },
  { name: "Japanese - 日本語", value: "ja" },
  { name: "Kannada - ಕನ್ನಡ", value: "kn" },
  { name: "Kazakh - қазақ тілі", value: "kk" },
  { name: "Khmer - ខ្មែរ", value: "km" },
  { name: "Korean - 한국어", value: "ko" },
  { name: "Kurdish - Kurdî", value: "ku" },
  { name: "Kyrgyz - кыргызча", value: "ky" },
  { name: "Lao - ລາວ", value: "lo" },
  { name: "Latin", value: "la" },
  { name: "Latvian - latviešu", value: "lv" },
  { name: "Lingala - lingála", value: "ln" },
  { name: "Lithuanian - lietuvių", value: "lt" },
  { name: "Macedonian - македонски", value: "mk" },
  { name: "Malay - Bahasa Melayu", value: "ms" },
  { name: "Malayalam - മലയാളം", value: "ml" },
  { name: "Maltese - Malti", value: "mt" },
  { name: "Marathi - मराठी", value: "mr" },
  { name: "Mongolian - монгол", value: "mn" },
  { name: "Nepali - नेपाली", value: "ne" },
  { name: "Norwegian - norsk", value: "no" },
  { name: "Norwegian Bokmål - norsk bokmål", value: "nb" },
  { name: "Norwegian Nynorsk - nynorsk", value: "nn" },
  { name: "Occitan", value: "oc" },
  { name: "Oriya - ଓଡ଼ିଆ", value: "or" },
  { name: "Oromo - Oromoo", value: "om" },
  { name: "Pashto - پښتو", value: "ps" },
  { name: "Persian - فارسی", value: "fa" },
  { name: "Polish - polski", value: "pl" },
  { name: "Portuguese - português", value: "pt" },
  { name: "Portuguese (Brazil) - português (Brasil)", value: "pt-BR" },
  { name: "Portuguese (Portugal) - português (Portugal)", value: "pt-PT" },
  { name: "Punjabi - ਪੰਜਾਬੀ", value: "pa" },
  { name: "Quechua", value: "qu" },
  { name: "Romanian - română", value: "ro" },
  { name: "Romanian (Moldova) - română (Moldova)", value: "mo" },
  { name: "Romansh - rumantsch", value: "rm" },
  { name: "Russian - русский", value: "ru" },
  { name: "Scottish Gaelic", value: "gd" },
  { name: "Serbian - српски", value: "sr" },
  { name: "Serbo - Croatian", value: "sh" },
  { name: "Shona - chiShona", value: "sn" },
  { name: "Sindhi", value: "sd" },
  { name: "Sinhala - සිංහල", value: "si" },
  { name: "Slovak - slovenčina", value: "sk" },
  { name: "Slovenian - slovenščina", value: "sl" },
  { name: "Somali - Soomaali", value: "so" },
  { name: "Southern Sotho", value: "st" },
  { name: "Spanish - español", value: "es" },
  { name: "Spanish (Argentina) - español (Argentina)", value: "es-AR" },
  { name: "Spanish (Latin America) - español (Latinoamérica)", value: "es-419" },
  { name: "Spanish (Mexico) - español (México)", value: "es-MX" },
  { name: "Spanish (Spain) - español (España)", value: "es-ES" },
  { name: "Spanish (United States) - español (Estados Unidos)", value: "es-US" },
  { name: "Sundanese", value: "su" },
  { name: "Swahili - Kiswahili", value: "sw" },
  { name: "Swedish - svenska", value: "sv" },
  { name: "Tajik - тоҷикӣ", value: "tg" },
  { name: "Tamil - தமிழ்", value: "ta" },
  { name: "Tatar", value: "tt" },
  { name: "Telugu - తెలుగు", value: "te" },
  { name: "Thai - ไทย", value: "th" },
  { name: "Tigrinya - ትግርኛ", value: "ti" },
  { name: "Tongan - lea fakatonga", value: "to" },
  { name: "Turkish - Türkçe", value: "tr" },
  { name: "Turkmen", value: "tk" },
  { name: "Twi", value: "tw" },
  { name: "Ukrainian - українська", value: "uk" },
  { name: "Urdu - اردو", value: "ur" },
  { name: "Uyghur", value: "ug" },
  { name: "Uzbek - o‘zbek", value: "uz" },
  { name: "Vietnamese - Tiếng Việt", value: "vi" },
  { name: "Walloon - wa", value: "wa" },
  { name: "Welsh - Cymraeg", value: "cy" },
  { name: "Western Frisian", value: "fy" },
  { name: "Xhosa", value: "xh" },
  { name: "Yiddish", value: "yi" },
  { name: "Yoruba - Èdè Yorùbá", value: "yo" },
  { name: "Zulu - isiZulu", value: "zu" },
];
